allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
onlyBuiltDependencies:
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
  - sharp
overrides:
  "@hono/node-server": ">=1.19.13"
  tar: ">=7.5.2"
