allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
overrides:
  reselect: 5.2.0

strictDepBuilds: true
minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade
