name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  ci-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULES_TOKEN }}

      - name: Setup mise
        uses: jdx/mise-action@main
        with:
          install: true

      - name: Prepare environment variables
        run: cp .env.example .env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Run Format & Lint Check with Biome
        run: pnpm biome ci ./src

      - name: Run Type Check
        run: pnpm tsc --noEmit

  build-and-deploy:
    name: Build and Deploy
    needs: ci-checks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULES_TOKEN }}

      - name: Setup mise
        uses: jdx/mise-action@main
        with:
          install: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --push \
            --tag "${{ env.REGISTRY }}/babcs2035/rusutsu:latest" \
            --tag "${{ env.REGISTRY }}/babcs2035/rusutsu:${{ github.sha }}" \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            .

      - name: Setup Tailscale
        uses: tailscale/github-action@main
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy package via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          target: ${{ secrets.DEPLOY_TARGET }}
          source: "docker-compose.production.yml"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            cd ${{ secrets.DEPLOY_TARGET }}
            mv docker-compose.production.yml docker-compose.yml
            docker compose pull
            docker compose up -d
            docker image prune -f
