name: CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULES_TOKEN }}

      - name: Setup mise
        uses: jdx/mise-action@main
        with:
          install: true

      - name: Prepare environment variables
        run: cp .env.example .env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate
        
      - name: Run Format & Lint Check with Biome
        run: pnpm biome ci ./src

      - name: Run Type Check
        run: pnpm tsc --noEmit
